// Generated by CoffeeScript 1.3.1
(function() {
  var PORT, http;

  http = require('http');

  PORT = 80;

  http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return res.end('Hello World\n');
  }).listen(PORT, '127.0.0.1');

  console.log('Server running at http://127.0.0.1:' + PORT);

}).call(this);
